# Generated by Django 3.1.4 on 2021-01-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonusGames',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='doneBonusGames',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='doneCashedOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='doneConsent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='doneInformation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='doneRequiredGames',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='doneSurvey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='doneTutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='requiredGames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='completionCode',
            field=models.CharField(default='JDEPv9FoorLvdwQiphRbNgChYftM2Whu', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
