# Generated by Django 3.1.4 on 2021-01-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210104_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completionCode',
            field=models.CharField(default='1KaxVoBauGVEItdJUIUjRfPKACls75Lu', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
