# Generated by Django 3.1.4 on 2021-01-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210105_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedback',
            field=models.CharField(blank=True, max_length=4200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='completionCode',
            field=models.CharField(default='hicVPSfo9Egxu06ds0CfNFqrlr8TUfgr', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
