# Generated by Django 3.1.4 on 2021-01-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210106_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=str, max_length=100, null=True)),
                ('blob', models.BinaryField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='agentType',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='matchFactor',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='nIter',
            new_name='rounds',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agentBlob',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='updateDB',
        ),
        migrations.AlterField(
            model_name='user',
            name='completionCode',
            field=models.CharField(default='z0sFRpykuBfNlFuOdFFtn4iG6Iwwxtt1', help_text='MTurk Confirmation Code', max_length=32),
        ),
        migrations.AddField(
            model_name='agent',
            name='blob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.blob'),
        ),
    ]
