# Generated by Django 3.1.4 on 2021-01-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210113_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='learner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='player',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='completionCode',
            field=models.CharField(default='VQB3jaYajjCQdBRjODjCPARClQxmdusN', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
