# Generated by Django 3.1.5 on 2021-02-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20210205_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=str, max_length=10000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='user',
            name='completionCode',
            field=models.CharField(default='4Yixx8NMc2BYQkZQlxInMJqSIbHTz9XB', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
