# Generated by Django 3.1.5 on 2021-02-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20210209_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(blank=True, default=str, max_length=4200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='completionCode',
            field=models.CharField(default='OMZ3RmOAhshXVqYZmofXHlAOPc30SChX', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
