# Generated by Django 3.1.5 on 2021-02-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20210209_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='user',
            name='completionCode',
            field=models.CharField(default='zgV5tqCVNXzUxWnFzylimtqgE511arza', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
