# Generated by Django 3.1.5 on 2021-02-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20210209_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completionCode',
            field=models.CharField(default='Aqmby8AioNwkfz33t3cmSFxpEAZwL7T2', help_text='MTurk Confirmation Code', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.FloatField(blank=True, choices=[('', '---'), ('1', 'Less than $20,000'), ('2', '$20,000 - 40,000'), ('3', '$40,000 - 60,000'), ('4', '$60,000 - 80,000'), ('5', '$80,000 - 100,000'), ('6', 'Greater than $100,000')], max_length=300, null=True),
        ),
    ]
