# Generated by Django 3.1.6 on 2021-02-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20210210_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='completionCode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doneBonusGames',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doneCashedOut',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doneInformation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doneRequiredGames',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gamesPlayed',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='QX4QtUHnm91Anq0xxY3lfOR4LnwENb62', help_text='MTurk Confirmation Code', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='doneBonus',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='doneCash',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='doneRequired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='nRequired',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='doneConsent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='doneSurvey',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='doneTutorial',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
