# Generated by Django 3.1.6 on 2021-02-12 23:10

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20210212_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('1', 'forgive'), ('2', 'punish')], default=game.models.User.f, max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='3B5kWHaELiYXjKN7TxGN94s14tCRDa51', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
