# Generated by Django 3.1.6 on 2021-02-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20210212_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='pUDs8Mlj5UDrNeS7HrZanA3bhFxU301t', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
