# Generated by Django 3.1.6 on 2021-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20210214_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='u33OfD022RaCpREh2d9SjtP77JEWwcUa', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
