# Generated by Django 3.1.6 on 2021-02-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20210214_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='Mpru6ELqt71Ynxg5xp9kRE9Bl3gPzeIe', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
