# Generated by Django 3.1.6 on 2021-02-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20210214_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='dO88KhxLAYP9isUDeO7P2DrduxGOiUKy', help_text='MTurk Confirmation Code', max_length=32),
        ),
    ]
