# Generated by Django 3.1.6 on 2021-02-19 06:24

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20210219_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='altruism',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='4CXqZ0Lax4732gQIgeu6LuwUEuTNjbBh', help_text='MTurk Confirmation Code', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='empathy',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('1', 'forgive'), ('2', 'punish')], default=game.models.User.f, max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='risk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
