# Generated by Django 3.1.7 on 2021-02-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20210219_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='RtOiAChsNFmf4sngnozDUthVrPF2g9AJ', help_text='MTurk Confirmation Code', max_length=300),
        ),
    ]
