# Generated by Django 3.1.7 on 2021-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20210223_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='winnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='Sg3Ifoc3c23Wt9fmhbm4mpjLhhsDtSmR', help_text='MTurk Confirmation Code', max_length=300),
        ),
    ]
