# Generated by Django 3.1.7 on 2021-03-01 18:42

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20210301_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currentGame',
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=game.models.User.g, help_text='MTurk Confirmation Code', max_length=300),
        ),
    ]
