# Generated by Django 3.1.7 on 2021-03-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_auto_20210301_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentGame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentGame', to='game.game'),
        ),
    ]
