# Generated by Django 3.1.7 on 2021-03-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_user_currentgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='doneBonus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nBonus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nRequired',
        ),
        migrations.AddField(
            model_name='user',
            name='doneMax',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nGames',
            field=models.IntegerField(default=0),
        ),
    ]
