# Generated by Django 3.1.7 on 2021-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_user_mturk'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
