# Generated by Django 3.1.7 on 2021-03-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_game_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='tStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mturk',
            field=models.CharField(default=0, max_length=33, unique=True),
            preserve_default=False,
        ),
    ]
