# Generated by Django 3.1.7 on 2021-03-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_remove_game_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='doneRequired',
            new_name='doneGames',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doneHIT',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doneMax',
        ),
    ]
